CREATE INDEX `idx_phrase_examples_user_phrase_created` ON `phrase_examples` (`user_id`,`phrase_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `idx_phrase_progress_phrase_user` ON `phrase_progress` (`phrase_id`,`user_id`);--> statement-breakpoint
CREATE INDEX `idx_phrases_source_catalog` ON `phrases` (`source_type`,`catalog_order`);--> statement-breakpoint
CREATE INDEX `idx_phrases_owner_updated` ON `phrases` (`owner_id`,`updated_at`);
-- Keep the catalog available after runtime schema initialization is removed.
INSERT OR IGNORE INTO `phrases` (`id`,`text`,`pattern`,`ipa`,`translation`,`context`,`source_type`,`catalog_order`,`owner_id`,`status`,`created_at`,`updated_at`) VALUES
('preset-0','I don''t know if it''s','[I don''t know] [if it''s]','aɪɾəˈnoʊ ɪfɪts','','', 'preset',0,NULL,'pick',datetime('now'),datetime('now')),
('preset-1','you know what I mean','[you know] [what I mean]','jənoʊ wʌɾaɪ miːn','','', 'preset',1,NULL,'pick',datetime('now'),datetime('now')),
('preset-2','all you have to do is','[all you] [have to] [do is]','ɔːljə hæftə duːɪz','','', 'preset',2,NULL,'pick',datetime('now'),datetime('now')),
('preset-3','I didn''t know that it was','[I didn''t know] [that it was]','aɪ dɪdn̩ noʊ ðəɾɪwəz','','', 'preset',3,NULL,'pick',datetime('now'),datetime('now')),
('preset-4','it''s going to be a','[it''s] [going to be a]','ɪts gənə biːə','','', 'preset',4,NULL,'pick',datetime('now'),datetime('now')),
('preset-5','there''s a lot of it','[there''s a lot of it]','ðərzəlɑɾəvɪt','','', 'preset',5,NULL,'pick',datetime('now'),datetime('now')),
('preset-6','you''re gonna have to do it','[you''re gonna] [have to] [do it]','jərgənə hæftə duːɪt','','', 'preset',6,NULL,'pick',datetime('now'),datetime('now')),
('preset-7','at the end of the day','[at the end of the day]','əɾðiɛndəvðədeɪ','','', 'preset',7,NULL,'pick',datetime('now'),datetime('now')),
('preset-8','I would have thought that','[I would have] [thought that]','aɪwʊɾə θɔːtðət','','', 'preset',8,NULL,'pick',datetime('now'),datetime('now')),
('preset-9','what do you want me to do','[what do you] [want me to] [do]','wʌɾəjə wʌnmɪɾə duː','','', 'preset',9,NULL,'pick',datetime('now'),datetime('now')),
('preset-10','it should have been a','[it should have been a]','ɪtʃʊɾəbɪnə','','', 'preset',10,NULL,'pick',datetime('now'),datetime('now')),
('preset-11','I don''t know what to do','[I don''t know] [what to do]','aɪɾənoʊ wʌɾəduː','','', 'preset',11,NULL,'pick',datetime('now'),datetime('now')),
('preset-12','there have been a lot of','[there have been a] [lot of]','ðərəvbɪnə lɑɾəv','','', 'preset',12,NULL,'pick',datetime('now'),datetime('now')),
('preset-13','you don''t have to do that','[you don''t] [have to] [do that]','jədoʊn hæftə duːðæt','','', 'preset',13,NULL,'pick',datetime('now'),datetime('now')),
('preset-14','did you tell him about it','[did you] [tell him] [about it]','dɪdʒə tɛlɪm əbaʊɾɪt','','', 'preset',14,NULL,'pick',datetime('now'),datetime('now')),
('preset-15','it used to be a lot','[it used to be a] [lot]','ɪtjuːstəbiːə lɑt','','', 'preset',15,NULL,'pick',datetime('now'),datetime('now')),
('preset-16','I''ll let you know if','[I''ll let you know] [if]','aɪl lɛtʃə noʊ ɪf','','', 'preset',16,NULL,'pick',datetime('now'),datetime('now')),
('preset-17','that''s what I''m talking about','[that''s] [what I''m] [talking about]','ðæts wʌɾaɪm tɔːkɪŋəbaʊt','','', 'preset',17,NULL,'pick',datetime('now'),datetime('now')),
('preset-18','we should have done it','[we should have] [done it]','wiʃʊɾə dʌnɪt','','', 'preset',18,NULL,'pick',datetime('now'),datetime('now')),
('preset-19','what have you been up to','[what have you] [been up to]','wʌɾəvjə bɪnʌptə','','', 'preset',19,NULL,'pick',datetime('now'),datetime('now')),
('preset-20','you would have had to','[you would have] [had to]','jəwʊɾə hæɾə','','', 'preset',20,NULL,'pick',datetime('now'),datetime('now')),
('preset-21','I couldn''t get a hold of him','[I couldn''t] [get a hold of him]','aɪkʊdn̩ gɛɾəhoʊldəvɪm','','', 'preset',21,NULL,'pick',datetime('now'),datetime('now')),
('preset-22','there could have been a','[there could have been a]','ðərkʊɾəbɪnə','','', 'preset',22,NULL,'pick',datetime('now'),datetime('now')),
('preset-23','why don''t you just ask her','[why don''t you] [just ask her]','waɪdoʊntʃə dʒəstæskər','','', 'preset',23,NULL,'pick',datetime('now'),datetime('now')),
('preset-24','it doesn''t have to be that','[it doesn''t] [have to be] [that]','ɪtdʌzn̩ hæftəbi ðæt','','', 'preset',24,NULL,'pick',datetime('now'),datetime('now')),
('preset-25','he must have been the one','[he must have been] [the one]','imʌstəbɪn ðəwʌn','','', 'preset',25,NULL,'pick',datetime('now'),datetime('now')),
('preset-26','I don''t know about that','[I don''t know] [about that]','aɪɾənoʊ əbaʊðæt','','', 'preset',26,NULL,'pick',datetime('now'),datetime('now')),
('preset-27','that''ll have to do for now','[that''ll] [have to do] [for now]','ðæɾl̩ hæftəduː fərnaʊ','','', 'preset',27,NULL,'pick',datetime('now'),datetime('now')),
('preset-28','it wasn''t supposed to be','[it wasn''t] [supposed to be]','ɪtwʌzn̩ spoʊstəbi','','', 'preset',28,NULL,'pick',datetime('now'),datetime('now')),
('preset-29','I should have known that','[I should have known] [that]','aɪʃʊɾənoʊn ðət','','', 'preset',29,NULL,'pick',datetime('now'),datetime('now')),
('preset-30','what would you do if','[what would you] [do if]','wʌwʊdʒə duːɪf','','', 'preset',30,NULL,'pick',datetime('now'),datetime('now')),
('preset-31','so what do you do','[so] [what do you do]','soʊ wʌɾəjəduː','','', 'preset',31,NULL,'pick',datetime('now'),datetime('now')),
('preset-32','could you give me a','[could you] [give me a]','kʊdʒə gɪmiə','','', 'preset',32,NULL,'pick',datetime('now'),datetime('now')),
('preset-33','what did he say','[what did he say]','wʌɾɪɾiseɪ','','', 'preset',33,NULL,'pick',datetime('now'),datetime('now')),
('preset-34','how was he supposed to','[how was he] [supposed to]','haʊwəzi spoʊstə','','', 'preset',34,NULL,'pick',datetime('now'),datetime('now')),
('preset-35','just give ''em a','[just give ''em a]','dʒəsgɪvəmə','','', 'preset',35,NULL,'pick',datetime('now'),datetime('now')),
('preset-36','I did it for her','[I did it] [for her]','aɪdɪɾɪt fərər','','', 'preset',36,NULL,'pick',datetime('now'),datetime('now')),
('preset-37','and that''ll be the','[and that''ll be] [the]','ənðæɾl̩bi ðə','','', 'preset',37,NULL,'pick',datetime('now'),datetime('now')),
('preset-38','I think there''ll be a','[I think] [there''ll be a]','aɪθɪŋk ðɛrl̩biə','','', 'preset',38,NULL,'pick',datetime('now'),datetime('now')),
('preset-39','if there''d been','[if there''d been]','ɪfðərdbɪn','','', 'preset',39,NULL,'pick',datetime('now'),datetime('now')),
('preset-40','I''m gonna have to','[I''m gonna] [have to]','aɪmgənə hæftə','','', 'preset',40,NULL,'pick',datetime('now'),datetime('now')),
('preset-41','there used to be a','[there used to be a]','ðərjuːstəbiːə','','', 'preset',41,NULL,'pick',datetime('now'),datetime('now')),
('preset-42','you didn''t have to','[you didn''t] [have to]','jədɪdn̩ hæftə','','', 'preset',42,NULL,'pick',datetime('now'),datetime('now')),
('preset-43','that''s it, isn''t it','[that''s it] [isn''t it]','ðætsɪt ɪnɪt','','', 'preset',43,NULL,'pick',datetime('now'),datetime('now')),
('preset-44','get out of it','[get out of it]','gɛɾaʊɾəvɪt','','', 'preset',44,NULL,'pick',datetime('now'),datetime('now')),
('preset-45','an hour and a half','[an hour and a half]','ənaʊrənəhæf','','', 'preset',45,NULL,'pick',datetime('now'),datetime('now')),
('preset-46','it''s kind of a','[it''s kind of a]','ɪtskaɪndəvə','','', 'preset',46,NULL,'pick',datetime('now'),datetime('now')),
('preset-47','not at all','[not at all]','nɑɾəɾɔːl','','', 'preset',47,NULL,'pick',datetime('now'),datetime('now')),
('preset-48','let me know what you','[let me know] [what you]','lɛmiːnoʊ wʌtʃə','','', 'preset',48,NULL,'pick',datetime('now'),datetime('now')),
('preset-49','d''you know what I mean','[d''you know] [what I mean]','dʒənoʊ wʌɾaɪmiːn','','', 'preset',49,NULL,'pick',datetime('now'),datetime('now'));
