export const PRESET_PHRASES = [
  { text: "I don't know if it's", pattern: "[I don't know] [if it's]", ipa: "aɪɾəˈnoʊ ɪfɪts" },
  { text: "you know what I mean", pattern: "[you know] [what I mean]", ipa: "jənoʊ wʌɾaɪ miːn" },
  { text: "all you have to do is", pattern: "[all you] [have to] [do is]", ipa: "ɔːljə hæftə duːɪz" },
  { text: "I didn't know that it was", pattern: "[I didn't know] [that it was]", ipa: "aɪ dɪdn̩ noʊ ðəɾɪwəz" },
  { text: "it's going to be a", pattern: "[it's] [going to be a]", ipa: "ɪts gənə biːə" },
  { text: "there's a lot of it", pattern: "[there's a lot of it]", ipa: "ðərzəlɑɾəvɪt" },
  { text: "you're gonna have to do it", pattern: "[you're gonna] [have to] [do it]", ipa: "jərgənə hæftə duːɪt" },
  { text: "at the end of the day", pattern: "[at the end of the day]", ipa: "əɾðiɛndəvðədeɪ" },
  { text: "I would have thought that", pattern: "[I would have] [thought that]", ipa: "aɪwʊɾə θɔːtðət" },
  { text: "what do you want me to do", pattern: "[what do you] [want me to] [do]", ipa: "wʌɾəjə wʌnmɪɾə duː" },
  { text: "it should have been a", pattern: "[it should have been a]", ipa: "ɪtʃʊɾəbɪnə" },
  { text: "I don't know what to do", pattern: "[I don't know] [what to do]", ipa: "aɪɾənoʊ wʌɾəduː" },
  { text: "there have been a lot of", pattern: "[there have been a] [lot of]", ipa: "ðərəvbɪnə lɑɾəv" },
  { text: "you don't have to do that", pattern: "[you don't] [have to] [do that]", ipa: "jədoʊn hæftə duːðæt" },
  { text: "did you tell him about it", pattern: "[did you] [tell him] [about it]", ipa: "dɪdʒə tɛlɪm əbaʊɾɪt" },
  { text: "it used to be a lot", pattern: "[it used to be a] [lot]", ipa: "ɪtjuːstəbiːə lɑt" },
  { text: "I'll let you know if", pattern: "[I'll let you know] [if]", ipa: "aɪl lɛtʃə noʊ ɪf" },
  { text: "that's what I'm talking about", pattern: "[that's] [what I'm] [talking about]", ipa: "ðæts wʌɾaɪm tɔːkɪŋəbaʊt" },
  { text: "we should have done it", pattern: "[we should have] [done it]", ipa: "wiʃʊɾə dʌnɪt" },
  { text: "what have you been up to", pattern: "[what have you] [been up to]", ipa: "wʌɾəvjə bɪnʌptə" },
  { text: "you would have had to", pattern: "[you would have] [had to]", ipa: "jəwʊɾə hæɾə" },
  { text: "I couldn't get a hold of him", pattern: "[I couldn't] [get a hold of him]", ipa: "aɪkʊdn̩ gɛɾəhoʊldəvɪm" },
  { text: "there could have been a", pattern: "[there could have been a]", ipa: "ðərkʊɾəbɪnə" },
  { text: "why don't you just ask her", pattern: "[why don't you] [just ask her]", ipa: "waɪdoʊntʃə dʒəstæskər" },
  { text: "it doesn't have to be that", pattern: "[it doesn't] [have to be] [that]", ipa: "ɪtdʌzn̩ hæftəbi ðæt" },
  { text: "he must have been the one", pattern: "[he must have been] [the one]", ipa: "imʌstəbɪn ðəwʌn" },
  { text: "I don't know about that", pattern: "[I don't know] [about that]", ipa: "aɪɾənoʊ əbaʊðæt" },
  { text: "that'll have to do for now", pattern: "[that'll] [have to do] [for now]", ipa: "ðæɾl̩ hæftəduː fərnaʊ" },
  { text: "it wasn't supposed to be", pattern: "[it wasn't] [supposed to be]", ipa: "ɪtwʌzn̩ spoʊstəbi" },
  { text: "I should have known that", pattern: "[I should have known] [that]", ipa: "aɪʃʊɾənoʊn ðət" },
  { text: "what would you do if", pattern: "[what would you] [do if]", ipa: "wʌwʊdʒə duːɪf" },
  { text: "so what do you do", pattern: "[so] [what do you do]", ipa: "soʊ wʌɾəjəduː" },
  { text: "could you give me a", pattern: "[could you] [give me a]", ipa: "kʊdʒə gɪmiə" },
  { text: "what did he say", pattern: "[what did he say]", ipa: "wʌɾɪɾiseɪ" },
  { text: "how was he supposed to", pattern: "[how was he] [supposed to]", ipa: "haʊwəzi spoʊstə" },
  { text: "just give 'em a", pattern: "[just give 'em a]", ipa: "dʒəsgɪvəmə" },
  { text: "I did it for her", pattern: "[I did it] [for her]", ipa: "aɪdɪɾɪt fərər" },
  { text: "and that'll be the", pattern: "[and that'll be] [the]", ipa: "ənðæɾl̩bi ðə" },
  { text: "I think there'll be a", pattern: "[I think] [there'll be a]", ipa: "aɪθɪŋk ðɛrl̩biə" },
  { text: "if there'd been", pattern: "[if there'd been]", ipa: "ɪfðərdbɪn" },
  { text: "I'm gonna have to", pattern: "[I'm gonna] [have to]", ipa: "aɪmgənə hæftə" },
  { text: "there used to be a", pattern: "[there used to be a]", ipa: "ðərjuːstəbiːə" },
  { text: "you didn't have to", pattern: "[you didn't] [have to]", ipa: "jədɪdn̩ hæftə" },
  { text: "that's it, isn't it", pattern: "[that's it] [isn't it]", ipa: "ðætsɪt ɪnɪt" },
  { text: "get out of it", pattern: "[get out of it]", ipa: "gɛɾaʊɾəvɪt" },
  { text: "an hour and a half", pattern: "[an hour and a half]", ipa: "ənaʊrənəhæf" },
  { text: "it's kind of a", pattern: "[it's kind of a]", ipa: "ɪtskaɪndəvə" },
  { text: "not at all", pattern: "[not at all]", ipa: "nɑɾəɾɔːl" },
  { text: "let me know what you", pattern: "[let me know] [what you]", ipa: "lɛmiːnoʊ wʌtʃə" },
  { text: "d'you know what I mean", pattern: "[d'you know] [what I mean]", ipa: "dʒənoʊ wʌɾaɪmiːn" },
] as const;
